"function"!==typeof Object.create&&(Object.create=function(c){function e(){}e.prototype=c;return new e});$.fn.urlData={};$.fn.urlData.path;
(function(c,e,h,d){var f={init:function(a,b){this.elem=b;this.$elem=c(b);c.fn.urlData.path=c.fn.urlData.path==d?"":c.fn.urlData.path;this.options=c.extend({},c.fn.urlData.options,a);!1===this.options.previewLink?this.build():this.buildPreview()},build:function(){var a=this;a.$elem.addClass("urldata_data_parser");a.$elem.width(a.options.width);a.inputURL=c(a.template.input);a.inputURL.attr("placeholder",a.options.placeholder);a.buttonParse=c(a.template.button);a.buttonParse.val(a.options.buttonText);
a.inputHolder=c(a.template.inputHolder);a.inputURL.appendTo(a.inputHolder);a.inputURL.focus(function(){c(this).select()});a.buttonParse.appendTo(a.$elem);a.inputHolder.appendTo(a.$elem);a.buttonParse.on("click",function(b){a.viewport!=d&&a.viewport.slideUp("normal",function(){c(this).remove()});a.URL=a.inputURL.val();a.parseURL(b)})},buildPreview:function(){var a=this;a.$elem.hover(function(b){a.loadTimer=setTimeout(function(){a.loadPreview(b)},a.options.hoverTime)},function(b){clearTimeout(a.loadTimer)})},
loadPreview:function(a){o=this.getElementOffset();if(this.previewContainer==d){if(this.$elem.attr("data-urldata-load")==d){this.URL=null===this.options.previewURL?this.$elem.attr("href"):this.options.previewURL;if(this.URL==d)return console.log("Please insert href on Anchor tag or URL set to previewURL option."),!1;this.parseURL(a);this.$elem.attr("data-urldata-load",!0);this.loading=c(this.template.loading);this.loading.appendTo("body");this.loading.css({left:o.l+o.w+5,top:o.t+(o.h-this.loading.height())/
2});this.loading.fadeIn()}c(".urldata_preview_container[data-show]").removeAttr("data-show").fadeOut();return!0}if("true"==this.previewContainer.attr("data-show"))return!0;c(".urldata_preview_container[data-show]").removeAttr("data-show").fadeOut();this.previewContainer.attr("data-show",!0).stop(!0,!0).fadeIn();this.setPositionToElem(this.previewContainer);return!0},prepare:function(a){this.viewport=c(this.template.viewport);a&&(this.thumbnail=c(this.template.thumbnail),this.thumbnail.appendTo(this.viewport));
this.section=c(this.template.section);this.title=c(this.template.title);this.description=c(this.template.description);this.site_name=c(this.template.site_name);this.title.appendTo(this.section);this.description.appendTo(this.section);this.site_name.appendTo(this.section);this.section.appendTo(this.viewport);this.viewport.appendTo(this.$elem)},setData:function(a){var b=this;b.data=a;b.prepare(a.image.length);b.title.html(a.title);b.description.html(a.description);b.site_name.html(a.site_name);!1===
b.options.previewLink&&(b.title.on("click",function(a){b.titleEditable(a)}),b.description.on("click",function(a){b.descriptionEditable(a)}));a.image.length&&(b.setImages(a.image),a=b.thumbnail.find("img:eq("+b.currentImg+")"),a.attr("src"),a.load(function(){c(this).fadeIn();b.enableControl()}));!1===b.options.previewLink?b.viewport.slideDown():(b.collectData(),b.viewport.remove())},parseURL:function(a){var b=this;if(!b.isValidURL(b.URL))return console.log("Invalid URL. Please check URL!"),!1;b.disableControl();
b.inputHolder!=d&&(b.loading=c(b.template.loading),b.loading.appendTo(b.inputHolder),b.loading.css({top:parseInt(b.inputHolder.height()-b.loading.height())/2}).fadeIn("fast"));b.parser(b.URL).done(function(a,c){if(a.title!=d)return b.setData(a),!0;b.enableControl(!1);return!1}).fail(function(a,c){console.log("FAIL!"+c);b.enableControl(!1);return!1})},parser:function(){return c.post(c.fn.urlData.path+this.options.parserURL,{url:this.URL,minThumb:this.options.minThumbSize,thumbCount:this.options.thumbCount,
execTime:this.options.executionTime},function(a){},"json")},disableControl:function(){!1===this.options.previewLink&&(this.buttonParse.prop("disabled",!0),this.inputURL.prop("disabled",!0))},enableControl:function(a){a=a==d?!0:a;!0===a?this.collectData():!1!==this.options.previewLink&&this.$elem.removeAttr("data-urldata-load");!1===this.options.previewLink&&(this.buttonParse.prop("disabled",!1),this.inputURL.prop("disabled",!1));this.loading.remove()},setImages:function(a){var b=this;b.currentImg=
0;"string"==typeof a?b.addThumbnail(a):(1<a.length&&(b.thumbNav=c(b.template.thumbChooser),b.thumbPrev=b.thumbNav.find(".urldata-prev"),b.thumbNext=b.thumbNav.find(".urldata-next"),b.thumbNav.appendTo(b.thumbnail).fadeIn(),b.currentImg=a.length-1,b.thumbPrev.bind("click",function(c){c.preventDefault();if(b.currentImg==a.length-1)return!1;b.thumbnail.find("img:eq("+b.currentImg+")").fadeOut();b.thumbnail.find("img:eq("+ ++b.currentImg+")").fadeIn("normal",function(){b.collectData()})}),b.thumbNext.bind("click",
function(a){a.preventDefault();if(0==b.currentImg)return!1;b.thumbnail.find("img:eq("+b.currentImg+")").fadeOut();b.thumbnail.find("img:eq("+--b.currentImg+")").fadeIn("normal",function(){b.collectData()})})),c.each(a,function(a,c){b.addThumbnail(c)}))},titleEditable:function(a){var b=this;if(0<b.title.find("input").length)return!1;titleEditor=c(b.template.titleEditor);currentTitle=b.title.html();b.title.html(titleEditor);titleEditor.val(currentTitle).focus();titleEditor.on("keypress",function(a){if(13==
a.keyCode||27==a.keyCode)b.title.html(titleEditor.val()),titleEditor.off("keypress"),b.collectData()}).blur(function(){b.title.html(titleEditor.val());titleEditor.off("keypress");b.collectData()})},descriptionEditable:function(a){var b=this;if(0<b.description.find("textarea").length)return!1;b.description.wrapInner(b.template.descriptionEditor);description=b.description.find("textarea");0<e.navigator.userAgent.toLowerCase().indexOf("firefox")&&1<parseInt(description.attr("rows"))&&description.attr("rows",
parseInt(description.attr("rows"))-1);description.focus().on("keypress",function(a){if(13==a.keyCode||27==a.keyCode)b.description.html(description.val()).scrollTop(0),description.off("keypress"),b.collectData()}).blur(function(){b.description.html(description.val()).scrollTop(0);description.off("keypress");b.collectData()})},addThumbnail:function(a){image=c("<img>");safeImageURL=a;timer=setInterval(function(){"true"!=image.attr("data-loaded")?image.attr("src",safeImageURL+"&refresh="+Math.random()):
clearInterval(timer)},5E3);image.load(function(){image.attr("data-loaded","true")}).error(function(){image.attr("src",safeImageURL+"&refresh="+Math.random())});image.prop("src",safeImageURL);image.prependTo(this.thumbnail)},isValidURL:function(a){return!0},collectData:function(){var a=this;temp=a.viewport.clone();a.data.video&&(thumbnail=temp.find(".urldata_thumbnail"),thumbnail.addClass("urldata_video_play"),thumbnail.attr("data-video",a.data.video),thumbnail.attr("data-video-type",a.data["video:type"]),
thumbnail.attr("data-video-width",a.data["video:width"]),thumbnail.attr("data-video-height",a.data["video:height"]));if(a.data["image:width"]||a.data["image:height"])thumbnail=temp.find(".urldata_thumbnail"),thumbnail.addClass("urldata_image_show"),thumbnail.attr("data-image",a.data.image),thumbnail.attr("data-image-width",a.data["image:width"]),thumbnail.attr("data-image-height",a.data["image:height"]);temp.find("img:not(:eq("+a.currentImg+"))").remove();temp.find("img").removeAttr("style");temp.find("span.urldata_thumb_selector").remove();
temp.wrapInner(a.template.anchor);temp.find("a").prop("href",a.URL);null!==a.options.containerAnchorClass&&temp.find("a").addClass(a.options.containerAnchorClass);!1===a.options.previewLink?(a.collectedData==d&&(a.collectedData=c(a.template.collected),a.collectedData.attr("name",a.options.name),a.collectedData.attr("id",a.options.name),a.collectedData.appendTo(a.$elem)),a.collectedData.val(temp.html())):(a.previewContainer==d&&(a.previewContainer=c(a.template.previewContainer),a.previewContainer.appendTo("body")),
a.previewContainer.html(temp.html()),a.previewContainer.find("img").fadeIn(),closeBtn=c(a.template.previewClose),closeBtn.on("click",function(){a.previewContainer.removeAttr("data-show").fadeOut()}),closeBtn.appendTo(a.previewContainer),a.previewContainer.addClass("urldata_preview_shadow"),a.previewContainer.fadeIn(),a.previewContainer.find("a.urldata_finally_data").urlView({width:a.options.width}),a.setPositionToElem(a.previewContainer),a.loading.remove());a.options.onComplete(temp.html())},getElementOffset:function(){var a=
[];a.w=this.elem.offsetWidth;a.h=this.elem.offsetHeight;a.l=this.$elem.offset().left;a.t=this.$elem.offset().top;return a},setPositionToElem:function(a){o=this.getElementOffset();height=a.get(0).offsetHeight;width=a.get(0).offsetWidth;wWidth=c(e).width();switch(this.options.alignment.toLowerCase()){case "tl":left=o.l;a.addClass("topleftpreview");break;case "tr":left=o.l+o.w-width;left=0>=left?5:left;a.css({left:left,top:o.t-(height+2)});break;case "br":left=o.l+o.w-width;left=0>=left?5:left;a.css({left:left,
top:o.t+o.h+2});break;default:left=o.l,left=left+width>=wWidth?wWidth-width-25:left,a.css({left:left,top:o.t+o.h+2})}},template:{input:'<input type="text" id="target_url_input">',button:'<input type="button" id="urldata_parse_button">',inputHolder:'<div class="urldata_parse_txt"></div>',viewport:'<div class="urldata_meta_result"></div>',thumbnail:'<div class="urldata_thumbnail"></div>',section:'<section class="urldata_info_section"></section>',title:'<div class="urldata_title"></div>',description:'<p class="urldata_description"></p>',
site_name:'<div class="urldata_site_name"></div>',thumbChooser:'<span class="urldata_thumb_selector"><a href="#" class="urldata-prev">&lsaquo;</a><a href="#" class="urldata-next">&rsaquo;</a></span>',titleEditor:'<input type="text" name="urldata_title_input" id="urldata_title_input" class="gui-input"/>',descriptionEditor:'<textarea class="gui-input" id="urldata_description_textarea" ></textarea>',loading:'<span class="urldata_url_loading"></span>',anchor:'<a href="#" class="urldata_finally_data"></a>',
collected:'<textarea class="final_data_container" cols="60" rows="10"></textarea>',previewContainer:'<div class="urldata_preview_container" data-show="true"></div>',previewClose:'<i class="urldata_preview_x">&times;</i>'}},g={init:function(a,b){this.elem=b;this.$elem=c(b);this.options=c.extend({},c.fn.urlView.options,a);this.$elem.css("width",this.options.width);this.$elem.attr("target",this.options.target);this.build()},build:function(){this.$elem.find(".urldata_thumbnail")&&(this.thumbnail=this.$elem.find(".urldata_thumbnail"),
this.image=this.thumbnail.find("img"),this.imageURL=this.image.attr("src"));this.image!=d&&this.showProcess()},showProcess:function(){var a=this;a.loading=c('<span class="urldata_url_loading"></span>');a.loading.appendTo(a.thumbnail);a.loading.css({left:parseInt((a.thumbnail.width()-a.loading.width())/2),top:parseInt((a.thumbnail.height()-a.loading.height())/2),zIndex:a.thumbnail.children().length+1});a.loading.show();a.timer=setInterval(function(){"true"!=a.image.attr("data-loaded")?a.image.attr("src",
a.imageURL+"&refresh="+Math.random()):clearInterval(a.timer)},5E3);a.image.load(function(){clearInterval(a.timer);a.image.fadeIn("normal",function(){a.thumbnail.hasClass("urldata_video_play")&&a.setThumbIcon("play");a.thumbnail.hasClass("urldata_image_show")&&a.setThumbIcon("zoom");a.loading.hide();a.image.attr("data-loaded","true");a.image.off("load")})}).error(function(){a.image.attr("src",a.imageURL+"&refresh="+Math.random())})},doShow:function(){var a=this;a.thumbnail.one("click",function(b){b.preventDefault();
a.icon.hide();!0===a.options.btnLongShadow&&a.shadow.hide();a.thumbnail.hasClass("urldata_video_play")&&a.playVideo(b);a.thumbnail.hasClass("urldata_image_show")&&(a.loading.show(),a.showImage(b))})},playVideo:function(a){var b=this;b.thumbnail.animate({width:0},300,function(){b.thumbnail.hide();b.image.hide();precent=b.thumbnail.parent().width()/b.thumbnail.data("video-width");embed=c('<embed bgcolor="#bdc3c7">');embed.attr("src",b.thumbnail.data("video"));embed.attr("width",b.thumbnail.parent().width());
embed.attr("height",parseInt(b.thumbnail.data("video-height")*precent));b.thumbnail.css("height",parseInt(b.thumbnail.data("video-height")*precent));b.thumbnail.append(embed);b.thumbnail.css({clear:"both",width:"100%"}).slideDown()})},showImage:function(a){var b=this,d=new Image;d.onload=function(){b.loading.remove();b.thumbnail.animate({width:0},300,function(){b.thumbnail.hide();precent=b.thumbnail.parent().width()/b.thumbnail.data("image-width");b.image.attr("src",b.thumbnail.data("image"));b.image.attr("width",
b.thumbnail.parent().width());b.image.attr("height",parseInt(b.thumbnail.data("image-height")*precent));b.thumbnail.css("height",parseInt(b.thumbnail.data("image-height")*precent));b.thumbnail.css({clear:"both",width:"100%"}).slideDown("normal",function(){c(d).remove()})})};d.src=b.thumbnail.data("image")},setThumbIcon:function(a){this.icon=c("<i>");"play"==a&&this.icon.addClass("urldata_icon_play");"zoom"==a&&this.icon.addClass("urldata_icon_zoom");this.icon.appendTo(this.thumbnail);l=parseInt((this.thumbnail.width()-
this.icon.width())/2);t=parseInt((this.thumbnail.height()-this.icon.height())/2);this.icon.css({left:l,top:t});this.icon.fadeIn();this.doShow();!0===this.options.btnLongShadow&&(this.shadow=c('<i class="urldata_icon_shadow">'),this.shadow.css({left:l,top:t}),this.shadow.appendTo(this.thumbnail),this.shadow.fadeIn())}};c.fn.urlData=function(a){return this.each(function(){Object.create(f).init(a,this)})};c.fn.urlData.options={parserURL:"index.php?option=com_iconnect&view=ajaxcall&layout=get_data&tmpl=tigraajax",
safeImageURL:"index.php?option=com_iconnect&view=ajaxcall&layout=safe_image&tmpl=tigraajax",buttonText:"Parse",placeholder:"Enter a valid URL",name:"urldata_meta_data",width:"auto",thumbSize:150,minThumbSize:150,thumbCount:5,executionTime:30,containerAnchorClass:null,previewLink:!1,previewURL:null,hoverTime:500,alignment:"tl",onComplete:function(a){return!0}};c.fn.urlView=function(a){return this.each(function(){Object.create(g).init(a,this)})};c.fn.urlView.options={width:"auto",target:"_blank",btnLongShadow:!1}})(tQuery,
window,document);